# permissions for end users to view gameedges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gameedge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edge-operator
    app.kubernetes.io/part-of: edge-operator
    app.kubernetes.io/managed-by: kustomize
  name: gameedge-viewer-role
rules:
- apiGroups:
  - operator.difinative
  resources:
  - gameedges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - gameedges/status
  verbs:
  - get
