---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.difinative
  resources:
  - gameedges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - gameedges/finalizers
  verbs:
  - update
- apiGroups:
  - operator.difinative
  resources:
  - gameedges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.difinative
  resources:
  - scedges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - scedges/finalizers
  verbs:
  - update
- apiGroups:
  - operator.difinative
  resources:
  - scedges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.difinative
  resources:
  - standardedges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - standardedges/finalizers
  verbs:
  - update
- apiGroups:
  - operator.difinative
  resources:
  - standardedges/status
  verbs:
  - get
  - patch
  - update
