---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.difinative
  resources:
  - edges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - edges/finalizers
  verbs:
  - update
- apiGroups:
  - operator.difinative
  resources:
  - edges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.difinative
  resources:
  - usecases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - usecases/finalizers
  verbs:
  - update
- apiGroups:
  - operator.difinative
  resources:
  - usecases/status
  verbs:
  - get
  - patch
  - update
