# permissions for end users to edit standardedges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: standardedge-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edge-operator
    app.kubernetes.io/part-of: edge-operator
    app.kubernetes.io/managed-by: kustomize
  name: standardedge-editor-role
rules:
- apiGroups:
  - operator.difinative
  resources:
  - standardedges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - standardedges/status
  verbs:
  - get
