# permissions for end users to view usecasevitals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: usecasevitals-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edge-operator
    app.kubernetes.io/part-of: edge-operator
    app.kubernetes.io/managed-by: kustomize
  name: usecasevitals-viewer-role
rules:
- apiGroups:
  - operator.difinative
  resources:
  - usecasevitals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - usecasevitals/status
  verbs:
  - get
