# permissions for end users to edit usecases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: usecases-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edge-operator
    app.kubernetes.io/part-of: edge-operator
    app.kubernetes.io/managed-by: kustomize
  name: usecases-editor-role
rules:
- apiGroups:
  - operator.difinative
  resources:
  - usecases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.difinative
  resources:
  - usecases/status
  verbs:
  - get
