apiVersion: operator.difinative/v1
kind: UsecaseVitals
metadata:
  labels:
    app.kubernetes.io/name: usecasevitals
    app.kubernetes.io/instance: usecasevitals-sample
    app.kubernetes.io/part-of: edge-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: edge-operator
  name: usecasevitals-sample
spec:
  # TODO(user): Add fields here
  usecase: Game
